### ISSUE TITLE
./scripts/pull_all_510k.py fails while parsing delimited file

### ISSUE THREAD

**Issue by tsbischof** [tsbischof/fda#4]
On Ubuntu 18.04 with Python 3.8, running the pull script fails with:

> Traceback (most recent call last):
>   File "./scripts/pull_all_510k.py", line 7, in <module>
>     db_510k = fda.db.get_510k_db(force_download=True)
>   File "/home/tsbischof/src/tsbischof/fda/test/lib/python3.8/site-packages/fda/db.py", line 24, in get_510k_db
>     db = pandas.concat(map(lambda url: load_510k_db(url, root_dir, 
>   File "/home/tsbischof/src/tsbischof/fda/test/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
>     return func(*args, **kwargs)
>   File "/home/tsbischof/src/tsbischof/fda/test/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 294, in concat
>     op = _Concatenator(
>   File "/home/tsbischof/src/tsbischof/fda/test/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 348, in __init__
>     objs = list(objs)
>   File "/home/tsbischof/src/tsbischof/fda/test/lib/python3.8/site-packages/fda/db.py", line 24, in <lambda>
>     db = pandas.concat(map(lambda url: load_510k_db(url, root_dir, 
>   File "/home/tsbischof/src/tsbischof/fda/test/lib/python3.8/site-packages/fda/db.py", line 40, in load_510k_db
>     data = pandas.read_csv(io.StringIO(raw), delimiter="|")
>   File "/home/tsbischof/src/tsbischof/fda/test/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
>     return func(*args, **kwargs)
>   File "/home/tsbischof/src/tsbischof/fda/test/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
>     return _read(filepath_or_buffer, kwds)
>   File "/home/tsbischof/src/tsbischof/fda/test/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 488, in _read
>     return parser.read(nrows)
>   File "/home/tsbischof/src/tsbischof/fda/test/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1047, in read
>     index, columns, col_dict = self._engine.read(nrows)
>   File "/home/tsbischof/src/tsbischof/fda/test/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 223, in read
>     chunks = self._reader.read_low_memory(nrows)
>   File "pandas/_libs/parsers.pyx", line 801, in pandas._libs.parsers.TextReader.read_low_memory
>   File "pandas/_libs/parsers.pyx", line 857, in pandas._libs.parsers.TextReader._read_rows
>   File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
>   File "pandas/_libs/parsers.pyx", line 1925, in pandas._libs.parsers.raise_parser_error
> pandas.errors.ParserError: Error tokenizing data. C error: Expected 22 fields in line 64826, saw 23

No data folder is created but this looks like there is a potential parse issue with the delimited files used in the FDA archive.

**Comment by tsbischof** [comment]
The issue appears to be a malformed line number 64826 in `pmn96cur.txt`, which includes an extra delimiter. Starting with line 64826:
|||||||||||||||||||||
|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|
K201455|Quanta System Spa|Francesco  Dell'Antonio|Via Acquedotto 109||Samarate (Va)||IT|21017|21017|06/01/2020|06/30/2020|SESE|SU|GEX|Summary|SU||Special|N||Litho 150, Cyber Ho 150
K201457|Auxein Medical Private Limited|71164|Gaurav  Luthra|Plot No.168,169,170 Phase-IV, Sector 57, Kundli|Industrial area|Sonipath||IN|131028|131028|06/01/2020|04/06/2021|SESE|OR|NKB|Summary|OR||Traditional|N||Auxein Brand Vertaux 5.5 mm Pedicle Screw System
K201458|Delta International Services & Logistics S.r.l|Mariella  Giorgieri|Piazza Adriana 4||Rome||IT|00193|00193|06/01/2020|12/23/2020|SESE|NE|GZJ|Summary|NE||Abbreviated|N||Scrambler Therapy Technology (Model ST-5A)

This applicant [includes a `|` in their name](https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfPMN/pmn.cfm?ID=K201457), which is not properly escaped in this database summary file.

**Comment by tsbischof** [comment]
Sent email to `webmail@oc.fda.gov` with a description of the issue. It looks like a potential data entry issue on their site, which can hopefully be fixed.

In the meantime, we can hardcode a workaround for this line.
